<script lang="ts">
	import { onMount } from "svelte";
	import { goto } from "$app/navigation";
	import TranslationBox from "$lib/TranslationBox.svelte";

	const translations = {
		en: {
			viewFullImage: "View Full Image",
			close: "Close",
			returnHome: "Home",
			boxes: [
				{
					title: "The Fluorescent Lamp",
					subhead: "Introduction",
					imgs: ["FL Construction_Min.jpg", "Fluorescent_Basic Characteristics_Min.png"],
					description: [
						"The convenience and popularity of the linear fluorescent lamp is underscored by the fact that it accounts for a greater amount of light produced on our planet than any other light source.  It achieved this position of dominance by the 1970s and it is estimated that today it accounts for about 80% of the world's artificial light.  It can be manufactured in almost any shade of white as well as coloured versions.  It offers a low system cost, the lifetime is very long, it is fully dimmable and easy to use, and above all it achieves high luminous efficacies to yield a low cost of operation.  The large area of the tube results in a low surface luminance, and it is especially well suited to the efficient and glare-free general illumination of large spaces.  In 1980 its position was further strengthened by the introduction of the compact fluorescent lamp.  Figure F1 illustrates the construction of a typical fluorescent tube.",
						"The fluorescent tube is essentially a low pressure mercury discharge lamp.  At either end of the tube is an electrode coil, also known as the cathode, whose purpose is to inject a flow of electrons into the discharge space.  On account of its high operating temperature it is made from coiled tungsten wire, and is coated with various refractory oxides which increase its electron-emission efficiency.  During life the electrode disintegrates and leads to blackening of the tube ends.  To minimise the severity of blackening it is surrounded by a metallic shield.  This shield also serves to reduce the visible 100Hz flicker which appears in the vicinity of the electrodes when operated at ordinary mains frequencies.  The whole electrode assembly is mounted onto a glass stem assembly, the rim of which is fused to the end of the discharge tube to produce a sealed vessel.  Via a narrow glass tube which pierces the stem, the lamp is dosed with a small quantity of mercury and filled to low pressure with an inert gas, typically argon or argon mixed with neon, krypton or xenon.  In combination with the tube length and diameter, the choice of gas filling determines the lamp’s electrical properties.  A phosphor coating is applied to the internal surface and a metal cap at either end provides the electrical and mechanical connection with the luminaire.  The outer surface of the glass is often coated with an invisible silicone wax which breaks up films of moisture on lamps employed in humid environments.  Although invisible, this feature is of paramount importance in ensuring reliable starting.",
						"The physical dimensions of the fluorescent lamp play a certain role in defining its applications.  Thanks to the large physical size, the surface luminance is low and it rarely gives rise to glare.  The large source size also produces a highly uniform and shadow-free illumination.  In conjunction with its long life and high efficacy, this makes it ideally suited to the general illumination of large interior spaces.  Naturally the degree of optical control that can be attained from such a voluminous light source is limited, and this precludes it from accent and display lighting.  Exterior applications are relatively scarce owing to its rather low luminous flux, and the fact that its luminous flux decreases sharply at low ambient temperatures.",
						"The operating principle of the fluorescent lamp has very early origins, however its first practical form emerged in 1934 at the General Electric Company of England (Osram-GEC).  It created the first hot cathode tubes employing a positive column discharge in a low pressure mercury atmosphere, to generate short-wavelength UVC radiation which stimulated a fluorescent powder coating on the inner surface of the discharge tube.  This design lacked many of the features required to engineer it into a commercial product, and it is General Electric of USA who holds the title of being first to market a commercially viable fluorescent tube.  Its 1938 development bears many similarities to the modern lamps, but during the past 80 years this lamp has undergone numerous changes in materials and design to ensure that it has always held its leading position as the lamp which offers the lowest total cost of ownership in producing a high quality white light."
					]
				},
				{
					subhead: "Fluorescent Lamp Nomenclature",
					imgs: ["Fluorescent_British System_Min.png", "Fluorescent_Philips System_Min.png"],
					description: [
						"During the 1940s several nations and manufacturers introduced comprehensive systems of nomenclature to identify the many different kinds of fluorescent lamps which had become available. Some of the more commonly encountered systems are disclosed in the tables below.",
						"All codes begin MCF, the terminology for a low pressure mercury-fluorescent source, as defined under the general mercury discharge lamp nomenclature.  Codes are sometimes followed by /U which indicates universal burning position.",
						"All codes begin TL, the original Dutch terminology applied to low voltage fluorescent tubes, as opposed to the high voltage tubes that wereformerly existent for cold-cathode signage applications.  T=Tension (voltage), L=Laag (low).",
						'First letter "F" denotes Fluorescent tube.  A pair of numbers then denotes either the lamp wattage (for standard types), or the tube length in inches (for special types).  A letter T indicates the tubular construction followed by the glass diameter in eigths of an inch.  After a slash the colour is given, and finally any special features are indicated.'
					]
				},
				{
					subhead: "Choice of Colours",
					imgs: [
						"FL Colours_Min.jpg",
						"FL%20Kruithof%20Diagram_Min.jpg",
						"Fluorescent Lamp Colours1_Min.png",
						"Fluorescent Lamp Colours2_Min.png",
						"Fluorescent Lamp Colours3_Min.png",
						"Fluorescent Lamp Colours4_Min.png",
						"Fluorescent Lamp Colours5_Min.png"
					],
					description: [
						"Two key factors must be considered when specifying the colour of a fluorescent tube - the correlated colour temperature (CCT) and the colour rendering index (CRI).   The colour temperature is largely a matter of personal taste.  The general preference is to use cool colours for a business-like atmosphere (e.g. in offices, factories, shops) and warm colours for a social atmosphere (e.g. in hotels and the home).However there is considerable variation between different countries in terms of the most popular fluorescent light colour.  The clear favourite in both continental Europe and North America is 4000K Neutral White.  In the UK however the preference is for 3500K tubes, which strikes a balance between creating a professional atmosphere whilst providing a feeling of warmth for a friendly working environment.  In the colder climes of the Nordic countries the 3000K lamps are preferred, to provide a feeling of warmth when coming indoors.   Conversely the hot conditions in Southern Europe lead their populations to prefer a cold colour light, which provides the perception of escaping out of the heat into a cool and comfortable interior space.  In all of these countries however, the warmest 2700K tubes are preferred in home lighting where they come close to the favoured appearance of incandescent and halogen lighting.  These local preferences are contrasted strongly by practically the whole of Asia, where most sales are for the cool daylight lamps of 5000-6500K, even for residential lighting.  This is due to the different structure of the Asian eye, which lacks blue photoreceptor cells.  Light sources having a higher blue content are preferred by the people of those regions, to render colours more closely to reality.  Some more detailed applications for the different colour temperatures are detailed in Figure F2.",
						"When choosing the desired light colour it is crucial to stay within the boundaries of the empirically determined Kruithof diagram (Figure F3), so as to achieve a natural colour appearance.  The use of high colour temperatures at low illumination levels results in a depressing visual environment where colours appear flat and dull.  Conversely the use of warm colour temperatures at high illumination levels yields an unpleasant insipid yellow hue to the surroundings which disturb the feeling of well-being.  The matching of the illumination level to the desired colour temperature is a key point that is often overlooked in modern lighting design.",
						"With the launch of the first fluorescent tubes, the choice of colours was restricted to a single shade of 'White' plus seven vibrant colours.  The white was a neutral colour having a CCT of around 4000K.  Soon this was joined by a lower colour temperature known as 'Mellow' or 'Warm White'.  This was rapidly followed by a high colour temperature light intended to better match the 5600K of natural daylight, and these lamps were simply called 'Daylight'.  During the 1950s and in particular following the invention of the halophosphate materials, dozens of additional shades of white made their debut, and these were later augmented by the so called Deluxe colours - which offered the same colour temperature as earlier tubes but with superior colour rendering properties.  Around this time most manufacturers adopted a coding system in which a completely arbitrary two-digit number was introduced to define each colour.\n\t\tThis situation propagated until the early 1990s, by which time there was quite some confusion in the market.  This was not only because of the great number of different colours and codes, but also because each manufacturer and global region had its own nomenclature.  The situation was rationalised following the introduction of a highly logical three-digit colour coding system by GE-Thorn in 1990.  Such was the simplicity of this system that during the rest of that decade it was adopted by most other manufacturers, and has since been extended to other discharge and LED lamps.  The general structure is illustrated in Table F2, where the first digit defines the colour rendering group while the second and third denote the correlated colour temperature.",
						"Some manufacturers continue to dual-brand fluorescent tubes with their original two-digit serial codes in addition to the modern 3-digit system - for instance 33-540 or 54-765.  There is no logic to the older codes and they cannot be deciphered to reveal the colour properties without reference to the manufacturer's literature.  A fairly comprehensive cross-reference table of both historic as well as modern fluorescent colour codes from the key manufacturers is provided in Table F3."
					]
				},
				{
					title: "Technology",
					subhead: "Operating Principle",
					imgs: [
						"FL%20Phosphors%20Glowing_Min.jpg",
						"FL%20Thorn%20F40T12-640%20Half%20Coated_Min.jpg",
						"FL%20Thorn%20F40T12%204%20Coatings_Min.jpg",
						"FL Energy Balance F40T12_Min.jpg",
						"FL Energy Balance F32T8_Min.jpg"
					],
					description: [
						"The fluorescent tube produces visible light by the process of 'fluorescence'.  This term was first coined by the British scientist Sir George Stokes in 1852, following his observations on the mineral 'fluorite' which glows when irradiated with ultra-violet light.  Today the term is defined as the emission of light by a substance which has absorbed radiation of a differing wavelength - usually shorter than the emitted light.  Materials which exhibit this property are colloquially known within the lamp world as phosphors, and figure F4 illustrates a sample of various compositions glowing under UV stimulation (image courtesy Thorn-Elgar Phosphors Ltd.)",
						"These materials are often manufactured from quite exotic blends of various minerals and elements, and the colour of light emitted is dependent on their precise chemical composition.  Left in the open air for prolonged periods they can degrade and are easily damaged, so for optimum performance they should be sealed into a chemically inert environment where they are also protected from mechanical abrasion.  For practical purposes in the case of the fluorescent lamp, the powders are mixed up into paints which are coated onto the inner surface of a glass tube.  This is further processed as the envelope of an electric discharge lamp in which ultra-violet radiation is generated.  The tube is evacuated of all air and filled with a little mercury vapour plus a rare gas.  An electrical discharge can then be struck between a pair of electrodes at either end.  This ionises the mercury vapour, which produces a small amount of blue-green light and a tremendous quantity of short wave Ultra-Violet radiation at wavelengths of 253.7nm and 185.1nm.  What makes the fluorescent tube fundamentally so efficient is the extremely high efficiency with which it is able to convert electrical energy into this UV radiation.  Only a tiny proportion of visible light is radiated by the low pressure mercury discharge, this being predominately at the wavelengths of 405nm (violet), 436nm (blue), 546nm (green) and 577nm (yellow).  In combination these lines give the discharge a pale blue colouration, which can be seen in the photographs below.",
						"The UV is of course invisible and quite useless for lighting applications, but when it srikes the phosphor on the inner surface of the glass tube, it is converted into visible light.  Figure F5 shows a demonstration tube specially made up by Thorn Lighting, which has been left partially uncoated.  Here it is possible to see the bluish glow of the mercury discharge as well as the luminescent properties of the fluorescent coating - in this case a white emitting powder of calcium halophosphate doped with mangenese and antimony.",
						"There are dozens of different phosphors in use today - some of which radiate very broadly across many different wavelengths, others showing narrow band emission of just one colour.  By applying them in isolation or blended together, it is possible to achieve almost any desired colour or shade of white.  Figure F6 demonstrates the principle in another special tube from the Jules Thorn Laboratories at Enfield, London, which has been made up with a coating of red phosphor on the right, followed by a band of green, a band of blue, then with all three mixed together to produce white light, and finally on the left an uncoated region showing the mercury discharge inside.",
						"Incidentally, note how the discharge terminates primarily on the upper surface of the cathode - the lamp in the photograph is being operated on a switch-start circuit and the current is supplied via the upper lead wire to the electrode.  Over time as the electron-emissive coating is consumed, the discharge root will progressively move across to the other side of the cathode coil.",
						"The principal reason for the high performance of fluorescent lamps is the very high efficiency with which each of the aforementioned steps takes place.  Even though only about 3% of the power consumed is converted into visible light by the mercury discharge, some 63% of the input energy is converted into the shortwave UV-C radiation which drives the fluorescence process.  Over the years the thermal losses in the discharge column have been minimised by optimisation of the gas filling and lamp geometry, and heat losses at the electrodes have been reduced thanks to the highly efficient cathode designs found in modern lamps.  To illustrate the range of efficacies found in typical lamps on the market today, Figures F7 and F8 below show the energy balance of the classic 4-foot 40W T12 argon-filled tube with halophosphate coating and operating on a conventional magnetic ballast, alongside that of the modern 4-foot 36W T8 krypton filled tube with triphosphor coating, and operated on a high frequency electronic ballast.  The primary reason for the increased efficacy of the T8 tubes is the use of a krypton filling, which dramatically reduces power losses at the electrodes."
					]
				},
				{
					subhead: "The Fluorescent Lamp - Phosphors",
					imgs: [
						"FL Spectra Halophosphor_Min.jpg",
						"Fluorescent Lamp Phosphors.png",
						"FL Spectra Triphosphor_Min.jpg",
						"FL CRI Wheel 4K Halo vs Tri_Min.jpg",
						"FL TCO Halo vs Tri_Min.jpg",
						"FL Spectra Colours_Min.jpg"
					],
					description: [
						"The earliest fluorescent tubes employed a phosphor of Zinc Beryllium Silicate - the first material found to create white light with reasonable quality.  However the efficacy of the popular 5-foot tube using these materials was just 35 lumens per watt.  These phosphors were rapidly superseded once more efficient materials had been developed.",
						"The most commonly found tubes on the global lighting market employ an internal coating of Calcium Halophosphate materials (generally known simply as 'Halophosphate' tubes).  This revolutionary material was invented in 1942 by a group led by A.H. McKeag of Osram-GEC in London, and succeeded in almost doubling lamp efficacy.  More than any other invention, it is this breakthrough which is responsible for having propelled the fluorescent business into the vast market it enjoys today.  However by modern standards, the halophosphate materials are relatively inefficient and deliver inferior lighting quality compared to newer technologies.  Although such tubes have a low initial purchase cost, this is rapidly offset by the increased electrical power consumption required to generate a given amount of light.  Owing to their reduced energy efficiency, Halophosphate tubes will shortly be phased out under EU legislation to enforce the adoption of other more efficient fluorescent phosphor materials.A wide variety of different whites can be created by the halophosphate system.  The phosphor is in fact a blend of two different materials which radiate broadly in the blue and orange parts of the spectrum respectively.  By changing the ratio of the two components a full range of warm to cool white hues can be achieved.  Some typical spectral power distributions for the Warm, Cool and Daylight White Halophosphate lamps are illustrated in Figure F9, which reveals the changing ratio of the blue and orange radiating components.  The colour rendering index is typically 50 to 70 and the lamp efficacy approx. 60 - 75 lm/W.",
						"During the 1970s a great deal was learned about human vision systems, and this spurred fluorescent research into new territories.  Traditionally it had been believed that to achieve good colour rendering, it was important for the lamp to produce a full spectrum with light of all wavelengths present.  However the human eye is not equally sensitive to all colours.  Therefore if a lamp is built to radiate all wavelengths, much of it will occur in regions to which the eye is less sensitive. New insights into the perception of colour vision discovered that it should be possible to achieve a very high colour rendering index from a light source having a narrow tri-band spectrum.  These three bands correspond to the red, green and blue photo-receptors in the eye.  It was theoretically proposed by the Westinghouse company in the USA to develop a prime-colour tube with three peaks at 450nm (blue), 540nm (green) and 610nm (orange) to coincide with the mechanisms of human colour vision.\n\t\tNew materials were synthesised with emissions close to these targets, and the modern family of Triphosphor lamps was born.  One of each of the following blue, green and red fluorescent components are generally employed in modern triphosphor tubes:",
						"By blending together the blue, green and red components in the correct proportions, a net white output of various hues can be realised.  The distinctive triple-peak spectra of the triphosphor colours are illustrated in Figure F10 for three popular shades of white.  Note that the cooler the colour temperature, the greater the proportion of blue light in the spectrum.",
						"Owing to the proximity of these peaks to the colour receptors in the human eye, a very high colour rendering index is achieved.  Typically this is of the order of Ra85 for most products, which marks a considerable improvement over Halophosphate materials.  The two CRI wheel diagrams in Figure F11 compare the colour rendering quality of a typical neutral white triphosphor tube with a halophosphate lamp delivering the same colour temperature.  It will at once be appreciated that the triphosphor technology shows far superior rendition of almost all of the fourteen CIE test colours.  In particular they offer an enormous improvement in the score for the R9 index, representing saturated red colours.  Triphosphor lamps offer tremendous added value in applications where colour rendering quality is important, for instance a retail sales environment.",
						"An unexpected advantage of these deeply saturated coloured phosphors was their astonishing efficiency of converting UV into visible light.  As a result lamp efficacy is boosted to levels of around 80 - 95 lm/W.  Perhaps the only reason for the lack of penetration of triphosphor materials is their high cost.  It is often said that the cost of coating a fluorescent lamp with ordinary halophosphor mixtures is analgous with the price of flushing the glass tubes with milk - whereas the triphosphor solutions are more akin to filling the tubes with a good scotch whisky!  This is due largely to the scarcity and cost of the rare earth activator materials employed in the triphosphor components, such as Europium, Cerium and Terbium.  The pure cost difference of triphosphor lamps puts off many consumers who prefer to remain with basic products, but really this is a false economy.  The less efficient halophosphate tubes consume far more than this initial investment through their greater electrical power consumption that is required to produce a given amount of light during lifetime.  The rapid payback interval for triphosphor tubes is illustrated in the cost of ownership graphic in Figure F12.  It can be seen that while the triphosphor lamps cost roughly twice as much to purchase, this initial expenditure is rapidly recouped through lower electricity consumption costs for a fixed lighting level.",
						"Current research into light and its effects on the human psyche are continuing to drive lamp technology into exciting new areas, and recent years have witnessed a number of special colour tubes which are intended to create an enhanced sense of well-being.  Originally developed to treat the medical condition SAD (Seasonal Affective Disorder), they feature a very high colour temperature thanks to a boosted blue component.  The actual colour temperature of these new tubes is pitched between 8000K and 17000K depending on the manufacturer.\n\tThe balance of phosphors has been engineered to strike what is currently believed to be the optimal balance between light for vision and light for personal well-being.   Tests carried out in factories, offices and schools reveal an astonishing increase in personal performance of 10% or more, with the subjects feeling more alert, awake and energised.\n\tThese new tubes are beginning to create a positive influence especially in windowless offices and dull classrooms, where their enhanced blue component mimics the presence of these wavelengths in natural daylight.  However as with all other colours, it is essential to bear in mind the teachings of the Kruithof diagram when installing light of such a high colour temperature.  Simply retrofitting these tubes into conventional luminaires can produce negative visual effects, because the human eye requires much more light as the colour temperature is increased.  Careful consideration must be given to the lux level on the working plane to ensure that compatibility is maintained with the very high colour temperature being provided.\n\tIn certain cases they can be mixed with warmer colour tubes with intelligent controls to achieve light levels and colours which match natural daylight conditions depending on the seasons and the time of day.",
						"The flexibility of fluorescent technology lends itself well to the generation of light colours other than white.  A full range of coloured tubes exists, as well as certain ultra-violet versions.  These have diverse applications such as sun tanning, photocopying, medical treatments, detection of forged bank notes, identification of minerals, entertainment lighting etc.  The spectra of some common tube colours are shown in the diagrams below, and their colour points are indicated on the CIE chromaticity triangle."
					]
				},
				{
					subhead: "The Fluorescent Lamp - Gas Fillings",
					description: [
						"All fluorescent lamps are essentially high vacuum lamps, filled to a very low pressure with one or more inert gases.  The gas performs several key functions in lamp operation, the most important of which are the following:\n\t\t\n\t\t\tIt reduces the required starting voltage for the discharge, such that it can be easily struck on simple control gear.  Different gases have different effects - for instance with Argon the starting is very easy but with Krypton it is somewhat more difficult.\n\t\t\tIt acts as a buffer gas to protect the electrodes, reducing the impact of ions which bombard them during the anode phase, and thereby reducing erosion of the electode by sputtering and evaporation.  This very greatly extends lamp life, the gases of higher molecular weight offering the greatest degree of protection of the electrodes.\n\t\t\tIt is adjusted to provide the right balance between rate of ionisation of mercury atoms (required to maintain the current flow through the lamp) and the excitation of mercury atoms so as to optimise the UV generation efficiency.\n\t\t\tIts presence randomises the direction of motion of free electons in the discharge to control their mean free path length and velocity.\n\t\t\n\tDepending on the lamp design and its intended application, the gas employed in commercially available products may be Argon, Krypton, Neon or Xenon - or invariably a mixture of at least two of these components at various different pressures.",
						'The earliest fluorescent tubes employed pure argon as their gas filling, and indeed this is still employed in the majority of T12 (38mm diameter) tubes for general lighting purposes.  Two T8 (26mm diameter) tubes employ an argon filling, these being the 15W 15" and 30W 36" types, which are today generally considered almost obsolete.  The modern family of T5 long tubes are also based on argon fillings.\n\t\tArgon is a relatively low cost gas which adequately performs all of the functions indicated above and yields high lamp effiacies with good service lifetime.  The optimal fill pressure lies in the range of around 2 to 5 torr.  The striking voltage to initiate the discharge is very low with argon, and these tubes can be operated on all types of electrical control gear.',
						"During the energy crisis of the 1970s considerable efforts were invested in improving the efficiency of the fluorescent lamp, owing to the enormous energy savings that could be realised on account of its tremendous popularity.  Many intriguing lamp concepts emerged during this period, but by far the most successful was the krypton-filled T8 lamp which acts as a retrofit for the conventional argon-filled T12 tubes.\n\t\tKrypton offers a major advantage over argon in that the electrical losses at the electrodes are dramatically reduced - from approximately 15% down to just 7% of the total power dissipated.  Proportionally more energy is therefore driven into the discharge column where it goes on to generate UV and useful light - see Figures 7 and 8 for a direct comparison.  The optimal filling pressure is around 1.5 to 2 torr.\n\t\tOne problem which affected Krypton lamps at the time of their introduction was the fact that the lamp voltage is lower than for an argon-filled tube.  Therefore when operated on existing ballasts, the krypton-filled lamps achieve a lower wattage rating and thereby deliver much less light.  This problem was circumvented by reducing the diameter of the glass tube from T12 (38mm) to T8 (26mm) diameter, which has the effect of increasing lamp voltage and this was successful in bringing the lamp wattage almost back up to normal levels.  In fact some wattage reduction for the T8 Krypton tubes was desirable so as to offer an energy saving of the T12 Argon originals, and the new wattages were established at levels approximately 10% lower.  Due to the fact that the Krypton T8 tube is more efficient than the Argon T12 tube, the luminous flux is approximately the same even though its power consumption is much reduced.  The only exception to this general rule is the 8-foot 100W tube, which is also a krypton-argon product intended to replace the original Argon 8-foot 125W tube, however at the time it was considered impractical to make such a long tube in T8 size glass owing to its fragility.  Therefore the energy saving associated with this tube is 25%, and the luminous flux is somewhat lower than for the argon original.\n\t\tAnother difficulty with the Krypton T8 tubes is that this gas requires a higher starting voltage than argon - a problem which is compounded by the smaller tube diameter.  To faciliatate starting the modern Krypton T8 tube actually consists of a 75%:25% Kr:Ar mixture.  Nevertheless the starting voltage is still somewhat higher, and these tubes normally work only on switch-start or electronic ballasts.",
						"Fillings of the noble gas Neon are employed in cases where a very high power loading per unit length of the lamp is necessary.  Contrary to Krypton which shows a reduced volt drop per unit length, neon can be used to increase the tube voltage.  It is used most frequently in the HO and VHO high output tubes which are popular for industrial lighting, particularly in North America, and also in other highly loaded tubes for special applications. \n\t\tOne difficulty with Neon is its low atomic mass, which offers little protection against the bombardment of the electrodes by high velocity ions during their anode phase of operation.  Neon is particularly destructive towards lamp electrodes, and it is customary to employ additional anode wires or plates to take some of the load away from the cathode coil, and thus minimise the liftime reduction when using this gas.",
						"A relatively recent development is the addition of Xenon to the gas filling, to achieve an additional energy saving over the krypton-filled T8 tubes.  This technique is employed in the latest generation of 'Eco' series T8 lamps which offer around 10% energy savings over the establised T8 Krypton versions.  Xenon causes a reduction in the discharge voltage, thus decreasing the power consumed by the tube on electromagnetic ballasts.  It does not however account for a significant improvement in lamp efficacy - that is achieved in the Eco tubes by phosphor improvements.\n\t\tOne primary drawback that has been identified with Xenon-filled Eco tubes is their extreme sensitivity to ambient temperature variations.  When operated under ideal conditions they can indeed achieve approximately 10% increase in efficacy over Krypton T8 types, but in many installations the light level is reduced dramatically if the ambient temperature is not suitable."
					]
				},
				{
					subhead: "The Fluorescent Lamp - Lifetime",
					imgs: ["FL Life Halo vs Tri_Min.jpg"],
					description: [
						"It is relatively complex to specify the lifetime of a fluorescent lamp, because it depends on several variables and can be defined in different ways.  Contrary to other light sources they do not always operate for long enough to reach an abrupt failure point, but may gradually lose their initial performance as they age.  Often the light output may decrease so much that the tube is considered useless and must be replaced even though it is still producing some light.  Alternatively the radiated light spectrum can change such that they no longer deliver the desired colour.  The useful lifetime of linear fluorescent lamps can vary from 6,000 hours to 60,000 hours depending on their construction, the operating conditions and type of control circuit.\n\t\tThe principal failure mechanism is a question of mortality and relates simply to exhaustion of the emissive coating on the electrodes at the tube ends.  When this point is reached the lamp will fail to start.\tLamps do not all reach this point at the same time - minute variations in manufacture lead to some achieving a longer or shorter life than others.  The useful lifetime is expressed in terms of a mortality curve, which illustrates the percent surviving lamps as a function of burning hours.  This is illustrated for Halophosphate and Triphosphor T8 in the diagram below.  The rated lifetime is usually given as when 50% of the tubes can be expected to have failed.\n\t\tThe mortality curve can be influenced very greatly by the switching frequency, and by the type of control gear.  Lamp ignition applies the greatest stress to the electrodes, and considerable quantities of electron emissive materials may be lost in the few seconds after starting.  It is possible to reduce this degradation by preheating the cathodes prior to application of the voltage pulse to strike the discharge.  With old switch-start control gear systems, the quality of the starter switch determines the extent and duration of cathode preheating.  Electronic ballasts having programmed starting provide much softer ignition and can greatly extend tube life.  Instant start systems are the most destructive and cause a significant reduction in lamp life.",
						"The second measure of lamp life is that of lumen depreciation.  This is quite rapid for the older halophosphate coatings, whereas modern Triphosphor materials achieve an admirable lumen maintenance.  End of life is generally specified when the luminous flux has dropped below 70% of the original value.\t\t\n\t\tFrom the 1990s onwards, as environmental regulations began to require significant reductions in the quantity of mercury dosed into each lamp, a relatively new failure mechanism of mercury starvation became apparent.  This did not affect older lamps, which were always dosed to great excess with mercury.\n\t\tDuring life mercury is consumed by various components, but above all by the glass wall.  If the initial dose is sufficiently small, the lamp may run out of mercury before either of the two principal failure mechanisms has ocurred.  When there is no available mercury remaining, the lamps acquire a pinkish appearance due to the colour of the discharge in the argon gas filling, and the absence of UV-C radiation for stimulation of the phosphor coating.\t\t\n\t\tThe rate of mercury loss has been decreased to suitably low levels only by the most advanced lamp manufacturers, which apply a pre-coating onto the glass to reduce the rate of mercury loss.  In parallel, the lumen depreciation of such lamps is almost halted.  The mechanism of mercury loss is due to its amalgamation with sodium ions contained within the glass.  The operation of the electric discharge causes a negative charge to appear on the inner wall of the glass, which draws sodium ions to the surface.  Some of these then form an amalgam with the mercury which not only binds it such that it can no longer take part in the discharge, it also causes a greyish coating to appear over the glass which reduces its light transmission.  \n\t\tThe solution is to apply a very thin coating to the inner surface of the glass, consisting a few nanometres thickness of aluminium oxide in the form of Alon C powder.  The coating must have extreme structural integrity and freedom from pinholes or cracks.  This acts as a barrier between the mercury and sodium and prevents amalgamation.  This pre-coating technology has allowed mercury weights to be drastically reduced, while also achieving exceptionally high lumen maintenance during life."
					]
				},
				{
					subhead: "The Fluorescent Lamp - Effect of Switching Frequency",
					imgs: ["FL Switching_Min.jpg"],
					description: [
						"Each switching causes progressive erosion of the electron-emissive materials with which the electrodes are coated.  The rated life will be achieved only when the frequency of switching does not exceed 8 times per 24 hours.  Increased switching frequency can result in a dramatic reduction of life.  Conversely the lamp can achieve up to double its rated life if it is switched on only once and never turned off again.  The strong inter-relation between switching frequency and lamp lifetime is illustrated in Figure F15 to the right.",
						"Once again there are several factors which influence the shape of this curve, most notably the type of control gear on which the lamp is operated.  Figure F15 represents the common situation of a magnetic ballast and glowbottle starter.  Depending on the type of ballast and starter and the extent of the electrode pre-heating that is foreseen, lamp life can vary dramatically.\n\t\tInstant start type ballasts do not deliver any preheat and can lead to a major reduction in useful lamp life.  More modern programmed-start electronic ballasts deliver a highly regulated preheating system and can realise considerable extensions in lamp lifetime by reducing the negative effects of switching on electrode life.\n\t\tStill more advanced electronic ballasts have been developed that deliver a constant voltage for the preheating of the cathodes, instead of the constant current that is normally supplied with conventional magnetic and electronic ballasts.  This is important because during lamp life, loss of electrode material decreases its mass and therefore a constant current will lead to a progressive increase in the preheating temperature, which drives the electrode to a swifter death.  The more expensive constant voltage system avoids this escalation in preheating temperatures and can deliver a remarkable increase in lamp lifetime.\t\t\n\tThe influence of switching frequency on lamp life must be borne in mind, for instance, when employing fluorescent tubes with movement detection systems for energy saving.  The frequent starting can result in a situation where tubes which would normally last for many years are completely worn out within a matter of months, and create a costly maintenance problem.  Special systems should be employed which will keep lamps burning for longer periods so as to reduce the effective switching cycle.   For further details and advice, refer to LIF Technical Statement No. 2."
					]
				},
				{
					subhead: "The Fluorescent Lamp - Effect of Ambient Temperature",
					imgs: ["FL Temperature_Min.jpg"],
					description: [
						"Fluorescent lamps are very sensitive to changes in the surrounding air temperature.  The graph in Figure F16 shows that peak efficacy is attained with an ambient temperature of around 25°C for the traditional T12 and T8 tubes, whereas the modern T5 products peak at 35°C.  Note that the actual tube wall temperature will be somewhat higher than ambient – typically around 40°C for a T8 lamp in an ambient 25°C environment.  A knowledge of these curves is of crucial importance when considering the lamp-luminaire combination to ensure maximum system efficacy.",
						"If the luminaire results in hotter operation, the lamp will fail to deliver the nominal luminous flux.  Here the newer T5 tubes have a distinct advantage.  They maintain their output better at high temperatures and deliver improved performance in modern, compact luminaires where higher temperatures are experienced.\n\t\tConversely in colder outdoor applications such as exterior sign lighting, it is clear that both T5 and T8 tubes would offer very low performance levels.  Here the T12 tube is generally the best option - although certain manufacturers now also produce T5 tubes specially optimised for low temperature operation.  Care must also be taken especially in modern arrangements where luminaires are used as air-handling devices, to ensure that a cool flow of air does not cause the lamp efficacy to be reduced.\n\t\tSpecial linear fluorescent lamps have in the past been offered by some manufacturers with an Indium Amalgam filling instead of the usual pure mercury dose.  This changes the vapour pressure of the mercury content so as to fine-tune the lamp for optimal output at high ambient temperatures, such as for instance in completely sealed luminaires where the tubes can reach rather high temperatures.  This tube was first developed by Thorn Lighting in 1965 and subsequently Philips and Osram versions were produced.  A more detailed overview can be found in Thorn Lighting Journal No. 3 pp.2-7."
					]
				},
				{
					subhead: "The Fluorescent Lamp - Effect of Operating Frequency",
					imgs: ["FL Frequency_Min.jpg"],
					description: [
						"Traditionally, fluorescent lamps have been operated at the same 50Hz or 60Hz frequency as the periodicity of the mains electricity supply.  However when the world's first installation of fluorescent lamps operating at high frequency was introduced, it was observed that lamp efficacy increased dramatically.  Figure F17 reveals that it is possible to increase luminous efficacy by almost 10% when driving the lamp at frequencies in excess of 2000 Hz.  This feature is capitalised on by the modern electronic ballast to achieve peak system efficacy from the lamp-ballast combination.",
						"The reason for this effect is relatively simple to understand.  In the case of an ordinary incandescent lamp operating on a 50-60Hz AC supply, the lamp delivers light during the entire period of the waveform.  At the instants when the voltage is lower than the peak value, the lamp still delivers light but a slightly lesser quantity.  Furthermore the thermal mass of the incandescent filament is such that it cannot heat up and cool down at the same rate as the current supply (except in case of extremely small lamps).  Thus despite the AC power source, the lamp delivers a continuous light output.\n\t\tFluorescent lamps are different in that below a certain threshold voltage, the discharge is extinguished and the lamp emits no light.  By increasing the supply frequency, the duration of the 'off' periods is proportionally reduced.  Increasing frequencies begin to approximate the situation of a constant current DC source, in which the discharge emits light continuously.  Owing to this phenomenon, the lamp emits more light.\t\t\n\t\tIncidentally, the first high frequency installation of fluorescent lamps was on the train carraiges of the London Undeground.  Formerly that company operated its own independent power station which generated a 400Hz mains frequency.  Owing to the fact that the inductance of a ballast varies as a function of its operating frequency, special units had to be engineered for this installation.  It was noted that their dimensions and mass were considerably less than for conventional 50-60Hz ballasts."
					]
				},
				{
					subhead: "The Fluorescent Lamp - Dimming Operation",
					description: [
						"Dimming of fluorescent lighting offers significant benefits - giving users control of their own lighting, and realising energy savings.   In certain environments it is a must, for instance in a lecture theatre to modify the lighting level when beaming a presentation.  In other applications the flexibility it gives to people has significant value, allowing them to match the illuminance on the working plane to their personal needs.\n\tThe control systems surrounding dimming of fluorescent lamps are becoming increasingly complex, for instance when linked to a daylight harvesting system to provide artificial lighting only at times of reduced natural illumination.  Dimming creates a rich visual experience and adds flexibility to any room, providing the right lighting environment for a variety of activities.\n\tAn added bonus is the fact that modern electronic ballasts permit a reduction in power consumption in parallel with the reduced light level, and this presents a valuable energy saving opportunity.  A further advantage is the use of dimming as an alternative to repeated on/off switching.  In this fashion substantial energy savings can be realised but without negatively impacting lamp life.\n\tTraditionally, dimming of fluorescent lamps has presented significant challenges.  If the power dissipation in the lamp is reduced too far, the electrode temperatures will fall such that their emission decreases and that leads to excessive wear and short life due to sputtering of the emissive material.  Cathode preheating needs to be maintained during dimming to the lower levels to avoid this problem.  Reignition of the discharge also becomes troublesome at very low currents, and in the past special tubes employing metal stripe ignition aids internally connected to one of the main electrodes were necessary.\n\tThe advent of the modern electronic ballast has greatly simplified matters.  By providing a variable signal voltage to the ballast, generally over the range 1 to 10 Volts, it can be triggered to regulate lamp power and automatically takes care of providing the necessary cathode heating and reignition voltage.  Standard lamp types can be used in all cases, and there is no further need to specify the former metal striped tubes."
					]
				}
			]
		},
		zh: {
			viewFullImage: "查看原图",
			close: "退出",
			returnHome: "首页",
			boxes: [
				{
					title: "荧光灯",
					subhead: "简介",
					imgs: ["FL Construction_Min.jpg", "Fluorescent_Basic Characteristics_Min.png"],
					description: [
						"线性荧光灯的便利性和受欢迎程度从其在地球上产生的光量超过任何其他光源这一事实中得到了强调。到20世纪70年代，它已经占据了主导地位，据估计如今它占全球人工光的约80%。它可以制造成几乎任何白色色调以及彩色版本。它具有较低的系统成本，使用寿命很长，可以完全调光，使用方便，最重要的是，它实现了高发光效率，从而降低了运行成本。灯管的大面积导致表面亮度低，特别适合于大面积空间的高效且无眩光的一般照明。1980年，紧凑型荧光灯的推出进一步巩固了其地位。图F1展示了典型荧光管的构造。",
						"荧光管本质上是一种低压汞放电灯。在灯管的两端各有一个电极线圈，也称为阴极，其作用是向放电空间注入电子流。由于其高工作温度，它由缠绕的钨丝制成，并涂有各种难熔氧化物，这些氧化物提高了其电子发射效率。在使用寿命期间，电极会分解，导致灯管两端变黑。为了最大限度地减少变黑的程度，它被一个金属屏蔽包围。这个屏蔽还有助于减少在普通市电频率下运行时在电极附近出现的可见100Hz闪烁。整个电极组件安装在一个玻璃灯脚组件上，其边缘与放电管的末端熔接在一起，形成一个密封的容器。通过穿过灯脚的一根细玻璃管，灯泡被注入少量汞，并用惰性气体（通常是氩气或氩气与氖气、氪气或氙气的混合物）充至低压。与灯管的长度和直径相结合，气体填充的选择决定了灯的电气特性。在内表面涂有一层荧光粉涂层，两端的金属灯头为灯具提供了电气和机械连接。玻璃的外表面通常涂有一层看不见的硅蜡，这种蜡可以破坏在潮湿环境中使用的灯泡上的水分薄膜。尽管看不见，但这一特性对于确保可靠启动至关重要。",
						"荧光灯的物理尺寸在一定程度上决定了它的应用范围。由于体积较大，表面亮度较低，很少产生眩光。大尺寸的光源还能产生非常均匀且无阴影的照明。结合其长寿命和高效率，这使其非常适合用于大面积室内空间的一般照明。自然地，从这种体积较大的光源能够获得的光学控制程度是有限的，这使其不适合用于重点照明和展示照明。由于其光通量相对较低，且在环境温度较低时光通量会急剧下降，因此其在室外的应用相对较少。",
						"荧光灯的工作原理起源很早，但其最早的实用形式于1934年出现在英国通用电气公司（Osram-GEC）。它创造了第一种采用低压汞环境中正柱放电的热阴极管，以产生短波长UVC辐射，激发放电管内表面的荧光粉涂层。这种设计缺乏许多将其工程化为商业产品的必要特性，而美国通用电气公司则是第一个将商业可行的荧光管推向市场的公司。其1938年开发的产品与现代灯具有许多相似之处，但在过去的80年里，这种灯在材料和设计上经历了许多变化，以确保它始终保持着作为生产高质量白光的灯具中总拥有成本最低的领先地位。"
					]
				},
				{
					subhead: "命名",
					imgs: ["Fluorescent_British System_Min.png", "Fluorescent_Philips System_Min.png"],
					description: [
						"在20世纪40年代，一些国家和制造商引入了全面的命名系统，以识别当时已有的许多不同类型的荧光灯。下面的表格中披露了一些较为常见的系统。",
						"所有代码以MCF开头，这是低压汞荧光光源的术语，根据通用汞放电灯命名法定义。代码有时会以/U结尾，表示通用燃烧位置。",
						"所有代码以TL开头，这是最初应用于低压荧光管的荷兰术语，与曾经用于冷阴极标识应用的高压管相对。T=Tension（电压），L=Laag（低）。",
						"第一个字母“F”表示荧光管。随后的一对数字表示灯泡功率（对于标准类型）或管长（以英寸为单位，对于特殊类型）。字母T表示管状结构，后面是玻璃直径（以八分之一英寸为单位）。在斜杠之后给出颜色，最后表示任何特殊功能。"
					]
				},
				{
					subhead: "颜色",
					imgs: [
						"FL Colours_Min.jpg",
						"FL%20Kruithof%20Diagram_Min.jpg",
						"Fluorescent Lamp Colours1_Min.png",
						"Fluorescent Lamp Colours2_Min.png",
						"Fluorescent Lamp Colours3_Min.png",
						"Fluorescent Lamp Colours4_Min.png",
						"Fluorescent Lamp Colours5_Min.png"
					],
					description: [
						"在指定荧光管的颜色时，必须考虑两个关键因素——相关色温（CCT）和显色指数（CRI）。色温主要是一个个人喜好的问题。一般来说，人们倾向于在营造商务氛围（如办公室、工厂、商店）时使用冷色，在营造社交氛围（如酒店和家庭）时使用暖色。然而，在最受欢迎的荧光灯颜色方面，不同国家之间存在相当大的差异。在欧洲大陆和北美，4000K中性白是绝对的最爱。然而，在英国，人们更倾向于3500K的灯管，这种颜色在营造专业氛围的同时，还能提供一种温暖的感觉，营造出友好的工作环境。在寒冷的北欧国家，人们更喜欢3000K的灯，因为当人们进入室内时，这种颜色能给人一种温暖的感觉。相反，在气候炎热的南欧，人们更倾向于使用冷色光，因为这种颜色能让人产生一种从炎热中解脱出来，进入一个凉爽舒适的室内空间的感觉。然而，在所有这些国家，人们在家庭照明中更喜欢最暖的2700K灯管，因为它们接近白炽灯和卤素灯的受欢迎外观。这些地方的偏好与整个亚洲形成了鲜明对比，在亚洲，大部分销售的都是5000-6500K的冷白光灯管，即使在住宅照明中也是如此。这是由于亚洲人眼睛的结构不同，他们的眼睛缺乏蓝色光感受器。那些地区的人们更喜欢蓝色含量较高的光源，因为这种光源能使颜色更接近真实。图F2详细列出了一些不同色温的更具体应用。",
						"在选择期望的光色时，至关重要的是要保持在经验确定的克鲁伊托夫图（图F3）的范围内，以实现自然的色彩外观。在低照度下使用高色温会导致令人沮丧的视觉环境，颜色显得平淡无光。相反，在高照度下使用暖色温会使周围环境呈现出令人不悦的苍白黄色调，扰乱人们的舒适感。将照度水平与期望的色温相匹配是现代照明设计中经常被忽视的一个要点。",
						"随着第一批荧光管的推出，颜色选择仅限于一种“白色”和七种鲜艳的颜色。白色是一种中性颜色，其相关色温约为4000K。很快，又出现了一种较低色温的颜色，被称为“柔和白”或“暖白”。紧接着，为了更好地匹配自然日光的5600K，又推出了一种高色温的光，这些灯管简单地被称为“日光”。在20世纪50年代，特别是在卤磷酸盐材料发明之后，数十种额外的白色色调首次亮相，后来又增加了所谓的豪华色——这些颜色与早期灯管的色温相同，但具有更优越的显色性能。大约在这个时候，大多数制造商采用了一种编码系统，引入了一个完全任意的两位数字来定义每种颜色。\n\t\t这种情况一直延续到20世纪90年代初，当时市场上存在相当多的混乱。这不仅是因为存在大量的不同颜色和代码，还因为每个制造商和全球地区都有自己的命名法。1990年，GE-Thorn引入了一个非常合乎逻辑的三位数字颜色编码系统后，这种情况得到了简化。这个系统的简单性使得在那个十年的剩余时间里，大多数其他制造商都采用了它，并且此后它已经被扩展到其他放电灯和LED灯。一般结构如表F2所示，其中第一位数字定义显色组，而第二位和第三位表示相关色温。",
						"一些制造商继续在现代三位数字系统之外，用他们最初的两位数字序列代码双重品牌荧光管——例如33-540或54-765。旧代码没有逻辑性，没有制造商的文献参考，无法破译以揭示颜色属性。表F3提供了一个相当全面的交叉参考表，包括主要制造商的历史和现代荧光灯颜色代码。"
					]
				},
				{
					title: "工艺",
					subhead: "工作原理",
					imgs: [
						"FL%20Phosphors%20Glowing_Min.jpg",
						"FL%20Thorn%20F40T12-640%20Half%20Coated_Min.jpg",
						"FL%20Thorn%20F40T12%204%20Coatings_Min.jpg",
						"FL Energy Balance F40T12_Min.jpg",
						"FL Energy Balance F32T8_Min.jpg"
					],
					description: [
						"荧光管通过“荧光”过程产生可见光。这个术语最早是由英国科学家乔治·斯托克斯爵士在1852年提出的，当时他观察到一种名为“萤石”的矿物质在紫外线照射下会发光。如今，该术语被定义为一种物质吸收不同波长（通常比发出的光短）的辐射后发出光的现象。在灯泡行业中，具有这种特性的材料通常被称为荧光粉，图F4展示了一些不同成分的荧光粉在紫外线刺激下发光的样本（图片由Thorn-Elgar荧光粉有限公司提供）",
						"这些材料通常由各种矿物和元素的独特混合物制成，发出的光的颜色取决于它们精确的化学成分。如果长时间暴露在空气中，它们会退化，并且很容易受损，因此为了达到最佳性能，它们应该被密封在一个化学惰性的环境中，在那里它们也受到机械磨损的保护。在荧光灯的实际应用中，这些粉末被混合成涂料，涂在玻璃管的内表面。随后，它被加工成一个产生紫外线的电放电灯的外壳。玻璃管被抽成真空，然后充入少量汞蒸气和一种稀有气体。然后可以在两端的一对电极之间产生电放电。这会使汞蒸气电离，产生少量蓝绿色光和大量波长为253.7纳米和185.1纳米的短波紫外线辐射。荧光管之所以从根本上如此高效，是因为它能够以极高的效率将电能转化为这种紫外线辐射。低压汞放电发出的可见光只占很小的一部分，主要在405纳米（紫罗兰色）、436纳米（蓝色）、546纳米（绿色）和577纳米（黄色）的波长处。这些光谱线结合起来使放电呈现出淡蓝色，这可以在下面的照片中看到。",
						"紫外线当然是看不见的，对于照明应用来说毫无用处，但当它击中玻璃管内表面的荧光粉时，就会转化为可见光。图F5展示了一根由Thorn Lighting特别制作的演示管，它部分未被涂层覆盖。在这里，可以看到汞放电的蓝色发光以及荧光涂层的发光特性——在这种情况下，是一种掺杂了锰和锑的钙卤磷酸盐白色发光粉末。",
						"如今有几十种不同的荧光粉在使用——其中一些在许多不同的波长上广泛辐射，而另一些则只显示单一颜色的窄带发射。通过单独使用它们或将它们混合在一起，可以实现几乎任何期望的颜色或白色阴影。图F6在伦敦恩菲尔德的朱尔斯·索恩实验室制作的另一根特殊管中展示了这一原理，该管右侧涂有一层红色荧光粉，接着是一条绿色带、一条蓝色带，然后将这三种混合在一起产生白光，最后在左侧是一块未涂层区域，显示内部的汞放电。",
						"顺便说一下，注意放电主要终止在阴极的上表面——照片中的灯泡是在一个开关启动电路上运行的，电流通过上引线供应给电极。随着时间的推移，电子发射涂层被消耗，放电根将逐渐移动到阴极线圈的另一侧。",
						"荧光灯高性能的主要原因是上述每个步骤都非常高效。尽管汞放电只将消耗的功率的约3%转化为可见光，但输入能量的63%被转化为驱动荧光过程的短波紫外线辐射。多年来，通过优化气体填充和灯泡几何形状，放电柱中的热损失已被最小化，而由于现代灯泡中高效的阴极设计，电极处的热损失也已减少。为了说明当今市场上典型灯泡的效率范围，图F7和图F8分别展示了经典4英尺40瓦T12充氩管（带有卤磷酸盐涂层）在传统电感镇流器上运行的能量平衡，以及现代4英尺36瓦T8充氪管（带有三基色涂层）在高频电子镇流器上运行的能量平衡。T8灯管效率提高的主要原因是使用了氪气填充，这大大减少了电极处的功率损失。"
					]
				},
				{
					subhead: "荧光粉",
					imgs: [
						"FL Spectra Halophosphor_Min.jpg",
						"Fluorescent Lamp Phosphors.png",
						"FL Spectra Triphosphor_Min.jpg",
						"FL CRI Wheel 4K Halo vs Tri_Min.jpg",
						"FL TCO Halo vs Tri_Min.jpg",
						"FL Spectra Colours_Min.jpg"
					],
					description: [
						"最早的荧光管使用了氧化铍锌硅酸盐荧光粉——这是第一种能够产生质量合理的白光的材料。然而，使用这些材料的流行的5英尺灯管的效率仅为每瓦35流明。一旦开发出更高效的材料，这些荧光粉很快就被取代了。",
						"在全球照明市场上最常见的灯管使用的是钙卤磷酸盐材料的内涂层（通常简称为“卤磷酸盐”灯管）。这种革命性的材料是由伦敦Osram-GEC的A.H.麦基领导的团队于1942年发明的，它几乎使灯管的效率翻了一番。没有任何其他发明比这一突破更能推动荧光灯业务发展到如今庞大的市场。然而，按照现代标准，卤磷酸盐材料相对效率较低，与新技术相比，照明质量也较差。尽管这种灯管的初始购买成本较低，但很快就会被产生一定量光所需的增加的电能消耗所抵消。由于其降低的能源效率，卤磷酸盐灯管将很快根据欧盟立法逐步淘汰，以强制采用其他更高效的荧光粉材料。通过卤磷酸盐体系可以创造出各种不同的白色。事实上，荧光粉是两种不同材料的混合物，它们分别在光谱的蓝色和橙色部分广泛辐射。通过改变这两种成分的比例，可以实现从暖白到冷白的完整色调范围。图F9展示了暖白、冷白和日光白卤磷酸盐灯的一些典型光谱功率分布，揭示了蓝色和橙色辐射成分的变化比例。显色指数通常为50到70，灯管效率约为每瓦60-75流明。",
						"在20世纪70年代，人们对人类视觉系统有了很多了解，这推动了荧光研究进入新的领域。传统上一直认为，为了实现良好的显色性，灯管产生全光谱、包含所有波长的光是很重要的。然而，人眼对所有颜色的敏感度并不相同。因此，如果灯管被设计成辐射所有波长，其中很多将发生在人眼敏感度较低的区域。对色彩视觉感知的新见解发现，应该可以从具有窄三带光谱的光源中实现非常高的显色指数。这三条带分别对应于眼睛中的红色、绿色和蓝色光感受器。美国西屋公司从理论上提出开发一种三原色灯管，在450纳米（蓝色）、540纳米（绿色）和610纳米（橙色）处有三个峰值，以与人类色彩视觉机制相匹配。\n\t\t合成的新材料发射光谱接近这些目标，现代三基色灯管家族诞生了。现代三基色灯管通常使用以下蓝色、绿色和红色荧光成分各一种：",
						"通过按正确比例混合蓝色、绿色和红色成分，可以实现各种色调的净白光输出。图F10展示了三基色灯管的三种流行白色色调的独特三峰光谱。请注意，颜色温度越低，光谱中蓝色光的比例越大。",
						"由于这些峰值接近人眼中的色彩感受器，因此实现了非常高的显色指数。通常，大多数产品的显色指数约为Ra85，这比卤磷酸盐材料有了显著的改进。图F11中的两个显色指数轮图比较了典型中性白三基色灯管与提供相同色温的卤磷酸盐灯的显色质量。可以立即看出，三基色技术在几乎所有14种CIE测试颜色的显色性方面都远远优于卤磷酸盐材料。特别是它们在R9指数（代表饱和红色）的得分上有了巨大的改进。在色彩显色质量重要的应用中，例如零售销售环境，三基色灯管提供了巨大的附加值。",
						"这些深饱和度彩色荧光粉的一个意外优势是它们将紫外线转换为可见光的惊人效率。因此，灯管效率提高到大约每瓦80-95流明的水平。也许三基色材料缺乏渗透的唯一原因是它们的成本较高。通常有人说，用普通卤磷酸盐混合物涂覆荧光灯的成本类似于用牛奶冲洗玻璃管的价格——而三基色溶液更像是用优质的苏格兰威士忌填充管子！这主要是由于三基色成分中使用的稀土激活材料（如铕、铈和铽）的稀缺性和成本。三基色灯管的纯成本差异使许多消费者望而却步，他们更愿意坚持使用基本产品，但这确实是一种虚假的经济。效率较低的卤磷酸盐灯管通过其在使用寿命期间产生一定量光所需的更大的电能消耗，消耗了比初始投资更多的电量。图F12中的总拥有成本图表说明了三基色灯管的快速回报期。可以看出，尽管三基色灯管的购买成本大约是卤磷酸盐灯管的两倍，但这种初始支出很快就会通过固定的照明水平下更低的电能消耗成本得到回收。",
						"目前对光及其对人类心理的影响的研究仍在继续推动灯管技术进入令人兴奋的新领域，近年来出现了一些特殊的彩色灯管，旨在创造一种增强的幸福感。这些灯管最初是为治疗季节性情感障碍（SAD）而开发的，由于蓝色成分的增加，它们具有非常高的色温。根据制造商的不同，这些新型灯管的实际色温在8000K到17000K之间。\n\t荧光粉的平衡经过工程设计，以达到目前认为是视觉光和个人幸福感光之间的最佳平衡。在工厂、办公室和学校进行的测试显示，个人表现惊人地提高了10%或更多，受试者感觉更加警觉、清醒和充满活力。\n\t这些新型灯管开始在无窗办公室和昏暗的教室中产生积极影响，它们增强的蓝色成分模仿了自然日光中这些波长的存在。然而，与其他所有颜色一样，在安装这种高色温的光时，必须牢记克鲁伊托夫图的教诲。简单地将这些灯管改装到传统灯具中可能会产生负面的视觉效果，因为随着色温的增加，人眼需要更多的光。必须仔细考虑工作平面上的照度水平，以确保与提供的非常高色温保持兼容。\n\t在某些情况下，它们可以与智能控制混合使用更暖色调的灯管，以实现与季节和一天中的时间相匹配的自然日光条件的光水平和颜色。",
						"荧光技术的灵活性使其非常适合产生非白色光。除了全系列的彩色灯管外，还有一些紫外线版本。这些灯管有多种用途，如晒黑、复印、医疗治疗、检测假钞、识别矿物、娱乐照明等。一些常见灯管颜色的光谱如下面的图表所示，它们的色点在CIE色度三角形上标出。"
					]
				},
				{
					subhead: "气体填充",
					description: [
						"所有荧光灯本质上都是高真空灯，充入一种或多种惰性气体，压力极低。气体在灯的运行中发挥着几个关键作用，其中最重要的是：\n\t\t\n\t\t\t它降低了放电所需的启动电压，使其能够在简单的控制装置上轻松启动。不同气体的效果不同——例如，用氩气启动非常容易，而用氪气则稍难。\n\t\t\t它作为缓冲气体保护电极，减少在阳极相期间撞击它们的离子的影响，从而减少电极因溅射和蒸发而受到的侵蚀。这极大地延长了灯的使用寿命，分子量较高的气体提供最大程度的电极保护。\n\t\t\t它被调整以在汞原子电离速率（维持灯内电流流动所必需）和汞原子激发之间提供正确的平衡，以优化紫外线生成效率。\n\t\t\t它的存在使放电中自由电子的运动方向随机化，以控制它们的平均自由程长度和速度。\n\t\t\n\t根据灯的设计及其预期用途，商业产品中使用的气体可能是氩气、氪气、氖气或氙气——或者通常是至少两种成分的混合物，压力各不相同。",
						"最早的荧光管使用纯氩气作为气体填充，实际上这仍然用于大多数T12（38毫米直径）的普通照明灯管。两种T8（26毫米直径）灯管也使用氩气填充，即15瓦15英寸和30瓦36英寸的灯管，这些灯管如今通常被认为几乎已经过时。现代T5长灯管系列也基于氩气填充。\n\t\t氩气是一种相对低成本的气体，能够充分执行上述所有功能，并提供高效率和良好的使用寿命。最佳填充压力在大约2到5托之间。用氩气启动放电的电压非常低，这些灯管可以在所有类型的电气控制装置上运行。",
						"在20世纪70年代的能源危机期间，由于荧光灯的巨大普及，人们投入了大量努力来提高其效率，因为可以实现巨大的节能。在这一时期出现了许多有趣的灯概念，但其中最成功的是氪气填充的T8灯，它作为传统氩气填充的T12灯管的替代品。\n\t\t氪气相对于氩气的主要优势在于，电极的电损耗显著降低——从大约15%降至总功耗的7%。因此，相对更多的能量被驱动到放电柱中，在那里它继续产生紫外线和有用的光——请参阅图7和图8进行直接比较。最佳填充压力约为1.5到2托。\n\t\t氪气灯在推出时面临的一个问题是，灯的电压低于氩气填充的灯管。因此，当在现有镇流器上运行时，氪气填充的灯达到的功率等级较低，因此提供的光量也少得多。通过将玻璃管的直径从T12（38毫米）减小到T8（26毫米）直径，解决了这个问题，这使得灯的电压增加，并成功地将灯的功率几乎恢复到正常水平。实际上，对于T8氪气灯管来说，一些功率降低是可取的，以便提供比T12氩气原件的节能，新的功率等级大约降低了10%。由于氪气T8灯管比氩气T12灯管更高效，即使其功耗大大降低，光通量也大致相同。这个一般规则的唯一例外是100瓦8英尺的灯管，这也是氪气-氩气产品，旨在替代原来的氩气8英尺125瓦灯管。然而，当时被认为由于其脆弱性，制作如此长的T8尺寸玻璃管是不切实际的。因此，这种灯管的节能为25%，光通量比氩气原件略低。\n\t\t氪气T8灯管的另一个问题是，这种气体比氩气需要更高的启动电压——这个问题由于管径较小而加剧。为了便于启动，现代氪气T8灯管实际上是由75%氪气和25%氩气的混合物组成。尽管如此，启动电压仍然略高，这些灯管通常只在开关启动或电子镇流器上工作。",
						"在需要每单位长度的灯管承载非常高功率的情况下，会使用氖气填充。与显示每单位长度电压降低的氪气不同，氖气可用于增加管电压。它最常用于HO和VHO高输出灯管，这些灯管在北美工业照明中尤其受欢迎，也用于其他特殊应用的高负载灯管。\n\t\t氖气的一个问题是其原子质量低，在阳极相期间，它对高速离子对电极的轰击提供的保护很少。氖气对灯管电极特别具有破坏性，通常会使用额外的阳极线或板来分担一些负载，从而减少使用这种气体时的寿命降低。",
						"一个相对较新的发展是在气体填充中加入氙气，以在氪气填充的T8灯管的基础上实现额外的节能。这种技术用于最新一代的“生态”系列T8灯，与已建立的T8氪气版本相比，可节省约10%的能源。氙气降低了放电电压，从而减少了灯管在电磁镇流器上消耗的功率。然而，它并没有显著提高灯管的效率——这是通过荧光粉改进在生态灯中实现的。\n\t\t已经确定的氙气填充生态灯的一个主要缺点是它们对环境温度变化极为敏感。在理想条件下运行时，它们确实可以实现比氪气T8类型大约10%的效率提升，但在许多安装中，如果环境温度不合适，光水平会显著降低。"
					]
				},
				{
					subhead: "寿命",
					imgs: ["FL Life Halo vs Tri_Min.jpg"],
					description: [
						"指定荧光灯的寿命相对复杂，因为它取决于几个变量，并且可以用不同的方式定义。与其他光源不同，它们并不总是运行足够长的时间以达到突然故障点，但可能会随着老化逐渐失去其初始性能。通常，光输出可能会降低到灯管被认为无用且必须更换的程度，即使它仍在发出一些光。或者，辐射光谱可能会发生变化，以至于它们不再提供所需的色彩。线性荧光灯的有用寿命可以从6000小时到60000小时不等，具体取决于其结构、运行条件和控制电路的类型。\n\t\t主要的故障机制是死亡率问题，仅仅与灯管两端电极上的发射涂层耗尽有关。当达到这一点时，灯将无法启动。灯并不是都在同一时间达到这一点——制造中的微小差异导致一些灯的寿命比其他灯长或短。有用寿命以死亡率曲线表示，该曲线说明了作为燃烧小时数函数的存活灯的百分比。下图说明了卤磷酸盐和三基色T8的情况。额定寿命通常给出为当50%的灯管预计已失败时的时间。\n\t\t死亡率曲线可能会受到开关频率和控制装置类型的巨大影响。灯的启动对电极施加了最大的压力，启动后的几秒钟内可能会损失大量的电子发射材料。通过在施加电压脉冲以点燃放电之前预热阴极，可以减少这种退化。在旧的开关启动控制装置系统中，启动器开关的质量决定了阴极预热的程度和持续时间。具有程序启动的电子镇流器提供了更柔和的点火，可以大大延长灯管寿命。即时启动系统最具破坏性，会导致灯寿命显著缩短。",
						"衡量灯寿命的第二个指标是光通量的衰减。对于较老的卤磷酸盐涂层，这种衰减相当快，而现代三基色材料实现了令人钦佩的光通维持。寿命末期通常规定为光通量降至原始值的70%以下。\n\t\t从20世纪90年代开始，随着环境法规开始要求大幅减少每只灯泡中注入的汞量，一种相对新的故障机制——汞匮乏开始出现。这种现象并未影响旧灯泡，因为旧灯泡总是注入过量的汞。\n\t\t在使用寿命期间，汞被各种部件消耗，尤其是玻璃壁。如果初始剂量足够小，灯可能在两种主要故障机制发生之前就耗尽了汞。当没有可用汞剩余时，由于氩气填充中的放电颜色以及缺乏紫外线来激发荧光粉涂层，灯泡呈现出粉红色。\n\t\t只有最先进的灯泡制造商通过在玻璃上涂覆一层预涂层来降低汞的损失速率，才将汞的损失速率降低到合适的低水平。与此同时，这种灯泡的光通量衰减几乎停止。汞损失的机制是由于它与玻璃中含有的钠离子形成合金。放电的运行导致玻璃内壁出现负电荷，吸引钠离子到表面。其中一些随后与汞形成合金，这不仅使汞固定，使其无法再参与放电，还在玻璃上形成一层灰色涂层，降低了其透光性。\n\t\t解决方案是在玻璃的内表面涂覆一层非常薄的涂层，由几纳米厚的氧化铝组成，以Alon C粉末的形式存在。涂层必须具有极高的结构完整性，且无针孔或裂缝。这在汞和钠之间形成了一个屏障，防止它们形成合金。这种预涂层技术使得汞的重量大幅减少，同时在使用寿命期间实现了异常高的光通维持。"
					]
				},
				{
					subhead: "开关频率的影响",
					imgs: ["FL Switching_Min.jpg"],
					description: [
						"每次开关都会导致电极上涂覆的电子发射材料逐渐侵蚀。只有当开关频率不超过每天24小时8次时，才能达到额定寿命。增加开关频率可能会导致寿命显著缩短。相反，如果灯只打开一次且不再关闭，其寿命可以达到额定寿命的两倍。开关频率与灯寿命之间的强烈相互关系如右侧的图F15所示。",
						"再次强调，有几个因素会影响这条曲线的形状，其中最显著的是灯所使用的控制装置类型。图F15代表了常见的磁性镇流器和辉光瓶启动器的情况。根据镇流器和启动器的类型以及预期的电极预热程度，灯的寿命可能会有很大差异。\n\t\t即时启动型镇流器不提供任何预热，可能会导致灯的使用寿命大幅缩短。更现代的程序启动电子镇流器提供了一个高度调节的预热系统，可以通过减少开关对电极寿命的负面影响来显著延长灯的使用寿命。\n\t\t还有一些更先进的电子镇流器已经开发出来，它们为阴极预热提供恒定电压，而不是传统磁性和电子镇流器通常提供的恒定电流。这很重要，因为在灯的使用寿命期间，电极材料的损失会减少其质量，因此恒定电流会导致预热温度逐步升高，从而加速电极的死亡。更昂贵的恒定电压系统避免了这种预热温度的上升，可以显著延长灯的使用寿命。\n\t\t在使用荧光管与运动检测系统以节省能源时，必须考虑到开关频率对灯寿命的影响。频繁启动可能会导致通常可以使用多年的灯管在短短几个月内就完全磨损，从而造成高昂的维护问题。应使用特殊的系统，使灯管持续燃烧更长时间，以减少有效的开关周期。有关更多详细信息和建议，请参阅LIF技术声明第2号。"
					]
				},
				{
					subhead: "环境温度的影响",
					imgs: ["FL Temperature_Min.jpg"],
					description: [
						"荧光灯对周围空气温度的变化非常敏感。图F16中的图表显示，传统T12和T8灯管在环境温度约为25°C时达到最高效率，而现代T5产品的峰值为35°C。请注意，实际的灯管壁温度会比环境温度稍高——通常在25°C环境温度下，T8灯管的温度约为40°C。了解这些曲线对于考虑灯具与灯管的组合以确保最大系统效率至关重要。",
						"如果灯具导致运行温度更高，灯将无法提供标称的光通量。在这方面，新型的T5灯管具有明显的优势。它们在高温下保持输出的能力更强，在现代紧凑型灯具中（这些灯具中温度较高）性能更好。\n\t\t相反，在寒冷的户外应用中，如外部标识照明，很明显T5和T8灯管都会提供非常低的性能水平。在这种情况下，T12灯管通常是最佳选择——尽管某些制造商现在也生产专门针对低温运行优化的T5灯管。在现代灯具中，灯具被用作空气处理设备，必须特别小心，以确保冷却的气流不会降低灯管的效率。\n\t\t过去，一些制造商曾提供过特殊线性荧光灯，这些灯使用铟汞齐填充，而不是通常的纯汞剂量。这改变了汞含量的蒸汽压，以微调灯管以在高环境温度下实现最佳输出，例如在完全密封的灯具中，灯管可能会达到相当高的温度。这种灯管最初由Thorn Lighting在1965年开发，随后Philips和Osram也生产了类似产品。更详细的概述可以在Thorn Lighting Journal No. 3 pp.2-7中找到。"
					]
				},
				{
					subhead: "运行频率的影响",
					imgs: ["FL Frequency_Min.jpg"],
					description: [
						"传统上，荧光灯一直以与市电周期相同的50Hz或60Hz频率运行。然而，当世界上第一个高频运行的荧光灯安装投入使用时，人们发现灯的效率显著提高。图F17显示，当以超过2000Hz的频率驱动灯时，可以将光效提高近10%。现代电子镇流器利用这一特性，从灯和镇流器的组合中实现最高的系统效率。",
						"这种效应的原因相对容易理解。在普通白炽灯以50-60Hz交流电运行的情况下，灯在整个波形周期内都提供光。在电压低于峰值的瞬间，灯仍然提供光，但数量略少。此外，白炽灯灯丝的热质量使得它无法像电流供应那样快速地加热和冷却（除非是非常小的灯）。因此，尽管使用交流电源，灯仍然提供连续的光输出。\n\t\t荧光灯不同之处在于，在低于某个阈值电压时，放电熄灭，灯不发光。通过提高供电频率，“关闭”期间的持续时间成比例地减少。增加频率开始近似于恒流直流电源的情况，其中放电连续发光。由于这种现象，灯发出更多的光。\n\t\t顺便说一句，第一个高频荧光灯安装是在伦敦地铁的列车车厢上。该公司以前有自己的独立发电站，产生400Hz的主频。由于镇流器的电感随其运行频率变化，必须为这一安装工程设计特殊的单元。人们注意到，它们的尺寸和质量明显小于传统的50-60Hz镇流器。"
					]
				},
				{
					subhead: "调光运行",
					description: [
						"荧光灯的调光提供了显著的好处——让用户能够控制自己的照明，并实现节能。在某些环境中，这是必须的，例如在演讲厅中，当播放演示文稿时需要调整照明水平。在其他应用中，它为人们提供的灵活性具有重要价值，使他们能够根据个人需求将工作平面上的照度与自己的需求相匹配。\n\t围绕荧光灯调光的控制系统变得越来越复杂，例如与日光采集系统连接，仅在自然照明减少时提供人工照明。调光创造了丰富的视觉体验，并为任何房间增加了灵活性，为各种活动提供了合适的照明环境。\n\t一个额外的好处是，现代电子镇流器允许随着光水平的降低而减少功耗，这提供了一个宝贵的节能机会。另一个优势是将调光作为频繁开关的替代方案。通过这种方式，可以实现显著的节能，而不会对灯的寿命产生负面影响。\n\t传统上，荧光灯的调光一直是一个重大挑战。如果灯中的功耗降低得太多，电极温度会下降，导致其发射减少，从而导致由于发射材料的溅射而过度磨损和寿命缩短。在调光到较低水平时需要保持阴极预热，以避免这个问题。在非常低的电流下重新点燃放电也变得麻烦，在过去，需要使用内部连接到主电极之一的金属条点火辅助装置的特殊灯管。\n\t现代电子镇流器的出现极大地简化了这一问题。通过向镇流器提供一个可变的信号电压，通常在1到10伏特之间，它可以被触发以调节灯的功率，并自动处理提供必要的阴极加热和重新点燃电压。在所有情况下都可以使用标准灯管类型，不再需要指定以前的金属条纹灯管。"
					]
				}
			]
		}
	};
	type Language = "zh" | "en";
	let language: Language = "en";

	onMount(() => {
		language = (localStorage.getItem("language") as Language) || "en";
		if (!translations[language]) {
			language = "en";
		}
	});
</script>

<TranslationBox {translations} {language} />

<button on:click={() => goto("/")} class="return-home">{translations[language].returnHome}</button>
